# Generated by Django 5.0.14 on 2025-08-02 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Conteúdo do Feedback')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('emissor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Emissor')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Receptor')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
