# Generated by Django 5.0.14 on 2025-08-01 21:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Ciclo')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('status', models.CharField(choices=[('Planejamento', 'Planejamento'), ('Ativo', 'Ativo'), ('Concluído', 'Concluído')], default='Planejamento', max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Ciclo de Avaliação',
                'verbose_name_plural': 'Ciclos de Avaliação',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome da Competência')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Competência',
                'verbose_name_plural': 'Competências',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RespostaAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(help_text='Nota de 1 a 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nota')),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='Justificativa')),
                ('data_resposta', models.DateTimeField(auto_now_add=True, verbose_name='Data da Resposta')),
                ('avaliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Avaliado')),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_feitas', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacoes.cicloavaliacao', verbose_name='Ciclo')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacoes.competencia', verbose_name='Competência')),
            ],
            options={
                'verbose_name': 'Resposta de Avaliação',
                'verbose_name_plural': 'Respostas de Avaliação',
                'unique_together': {('ciclo', 'avaliado', 'avaliador', 'competencia')},
            },
        ),
    ]
