# Generated by Django 5.0.14 on 2025-08-01 21:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avaliacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título do Objetivo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacoes.cicloavaliacao', verbose_name='Ciclo')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Objetivo',
                'verbose_name_plural': 'Objetivos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição do Resultado-Chave')),
                ('tipo', models.CharField(choices=[('Percentual', '%'), ('Financeiro', 'R$'), ('Numérico', 'Nº')], max_length=50, verbose_name='Tipo')),
                ('valor_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Valor Inicial')),
                ('valor_alvo', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor Alvo')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_chave', to='okr.objetivo', verbose_name='Objetivo')),
            ],
            options={
                'verbose_name': 'Resultado-Chave',
                'verbose_name_plural': 'Resultados-Chave',
                'ordering': ['objetivo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_atual', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor Atual do Check-in')),
                ('nota_confianca', models.IntegerField(help_text='De 1 (em risco) a 5 (no caminho certo)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nota de Confiança')),
                ('comentario', models.TextField(verbose_name='Comentário')),
                ('data_checkin', models.DateTimeField(auto_now_add=True, verbose_name='Data do Check-in')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
                ('resultado_chave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='okr.resultadochave', verbose_name='Resultado-Chave')),
            ],
            options={
                'verbose_name': 'Check-in',
                'verbose_name_plural': 'Check-ins',
                'ordering': ['-data_checkin'],
            },
        ),
    ]
