# Generated by Django 5.0.14 on 2025-08-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okr', '0002_resultadochave_progresso'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivo',
            name='progresso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Progresso (%)'),
        ),
    ]
