# Generated by Django 5.0.14 on 2025-08-01 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHumor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateField(auto_now_add=True, verbose_name='Data do Registro')),
                ('humor', models.IntegerField(choices=[(1, 'Muito Triste'), (2, 'Triste'), (3, 'Neutro'), (4, 'Feliz'), (5, 'Muito Feliz')], verbose_name='Humor')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentário')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Registro de Humor',
                'verbose_name_plural': 'Registros de Humor',
                'ordering': ['-data_registro'],
                'unique_together': {('colaborador', 'data_registro')},
            },
        ),
    ]
